global:
  appName: cards-service

replicaCount: 1

image:
  repository: umasankar33/5-retail-app-source-cards-service
  tag: 3

service:
  port: 8083

env:
  APP_PORT: "8083"

resources:
  limits: { cpu: "300m", memory: "256Mi" }
  requests: { cpu: "150m", memory: "128Mi" }