# Global tracking variables required by the shared template architecture
global:
  appName: retail-app

serviceName: frontend-service
replicaCount: 2
image:
  repository: umasankar33/5-retail-app-frontend
  tag: latest
service:
  port: 80
  type: LoadBalancer