global:
  appName: retail-app

serviceName: frontend-service
replicaCount: 2

image:
  repository: umasankar33/5-retail-app-frontend
  tag: latest

# Match our dynamic template fix
containerPort: 80
serviceType: LoadBalancer

service:
  port: 80
  type: LoadBalancer

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"