apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-service
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cards-service
  template:
    metadata:
      labels:
        app: cards-service
    spec:
      serviceAccountName: retail-app-sa
      containers:
      - name: cards-engine
        image: umasankar33/retail-app-source-cards-test:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
          name: http
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 15"]
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 20
        env:
        - name: PORT
          value: "8083"
        - name: LOG_LEVEL
          value: "info"
        - name: CARDS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: retail-secure-vault
              key: aes_gcm_key # Aligned to the direct extracted payload key
---
apiVersion: v1
kind: Service
metadata:
  name: cards-service
  namespace: retail-prod
spec:
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: cards-service
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cards-service-hpa
  namespace: retail-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cards-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cards-service-pdb
  namespace: retail-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cards-service