global:
  appName: catalog-service

replicaCount: 1

image:
  repository: umasankar33/5-retail-app-source-catalog-service
  tag: latest

service:
  port: 8082

env:
  GIN_MODE: "release"
  PORT: "8082"
  DB_HOST: "prod-retail-db.ap-south-1.rds.amazonaws.com"

resources:
  limits: { cpu: "200m", memory: "128Mi" }
  requests: { cpu: "50m", memory: "64Mi" }