apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retail-apps-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack # Binds directly to the Prometheus Operator scraper engine
spec:
  selector:
    matchLabels:
      monitoring-target: retail-microservice
  namespaceSelector:
    matchNames:
      - retail-prod
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 8s