apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standalone-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 7.x.x
    helm:
      values: |
        persistence: { enabled: false }
        adminPassword: "admin"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]