apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    webhook:
      url: "http://172.17.0.1:4566/"
      method: POST
      headers:
        'X-Amz-Target': "secretsmanager.GetSecretValue"
        'Content-Type': "application/x-amz-json-1.1"
      body: '{"SecretId": "{{ .remoteRef.key }}"}'
      result:
        # FIX: Tells the webhook parser to strip out the nested JSON encoding automatically
        jsonPath: "$.SecretString"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: retail-secure-vault-sync
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: retail-secure-vault
    creationPolicy: Owner
  # DataFrom uses the native parser engines to look up individual inner properties automatically
  dataFrom:
  - extract:
      key: prod/retail/db
  - extract:
      key: prod/retail/auth
  - extract:
      key: prod/retail/crypto