apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1 # Deploys directly targeting your AWS Bangalore infrastructure grid
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa #retail-app-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-sync
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: retail-secrets-backend
    kind: SecretStore
  target:
    name: internal-app-db-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      # CHANGE THIS FROM prod/retail/db TO YOUR DEV PATH:
      key: dev/retail/rds
