apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-shared-config
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
data:
  DB_HOST: "retail-db-service"
  DB_PORT: "5432"
  DB_NAME: "retail_storefront"
  DB_USER: "umasankar_admin"