global:
  appName: payment-service

replicaCount: 1

image:
  repository: 5-retail-app-source-payment-service
  tag: latest

service:
  port: 8085

env:
  PORT: "8085"

resources:
  limits: { cpu: "300m", memory: "256Mi" }
  requests: { cpu: "100m", memory: "128Mi" }