apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      serviceAccountName: retail-app-sa
      containers:
      - name: login-engine
        image: umasankar33/retail-app-source-login-test:1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: retail-secure-vault
              key: JWT_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: retail-prod
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: login-service
  type: ClusterIP
