global:
  appName: orders-service

replicaCount: 1

image:
  repository: 5-retail-app-source-orders-service
  tag: latest

service:
  port: 8084

env:
  JAVA_OPTS: "-Xms128m -Xmx256m"
  SERVER_PORT: "8084"

resources:
  limits: { cpu: "500m", memory: "512Mi" }
  requests: { cpu: "250m", memory: "256Mi" }