apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: retail-prod
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: nginx-web
        image: umasankar33/5-retail-app-frontend:v21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: retail-prod
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend-service
  type: NodePort # Plugs seamlessly directly into AWS ALB Target Groups
