apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.global.appName }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s