apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}
  # FIX: Allow ArgoCD to override or explicitly pass the release fallback
  namespace: {{ .Release.Namespace | quote }} 
  labels:
    app: {{ .Values.global.appName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.global.appName }}