apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: retail-microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Chinthaparthy-UmasankarReddy/5-tier-retail-infra-gitops.git'
        revision: dev
        directories:
          - path: apps/microservices/*
  template:
    metadata:
      name: '{{path.basename}}-app'
      annotations:
        # LOWER PRIORITY WAVE: Waits until Wave -1 (Prometheus Stack) is healthy
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/Chinthaparthy-UmasankarReddy/5-tier-retail-infra-gitops.git'
          targetRevision: dev
          path: apps/central-shared-chart
          helm:
            valueFiles:
              - '$git-repo/apps/microservices/{{path.basename}}/values.yaml'
        - repoURL: 'https://github.com/Chinthaparthy-UmasankarReddy/5-tier-retail-infra-gitops.git'
          targetRevision: dev
          ref: git-repo
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true