apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: retail-microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Chinthaparthy-UmasankarReddy/5-tier-retail-infra-gitops.git'
        revision: dev
        directories:
          - path: apps/microservices/*
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      sources:
        # Source 1: The Central Shared Skeleton Helm Chart
        - repoURL: 'https://github.com/Chinthaparthy-UmasankarReddy/5-tier-retail-infra-gitops.git'
          targetRevision: dev
          path: apps/central-shared-chart
          helm:
            # Point to the reference defined below in Source 2
            valueFiles:
              - '$git-repo/apps/microservices/{{path.basename}}/values.yaml'
              
        # Source 2: Define your Git root alias to load the values profiles
        - repoURL: 'https://github.com/Chinthaparthy-UmasankarReddy/5-tier-retail-infra-gitops.git'
          targetRevision: dev
          ref: git-repo
          
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true