global:
  appName: login-service

replicaCount: 1

image:
  repository: 5-retail-app-source-login-service # Matches your local Docker image string
  tag: latest

service:
  port: 8081

env:
  NODE_ENV: "production"
  PORT: "8081"
  DB_HOST: "prod-retail-db.ap-south-1.rds.amazonaws.com"

resources:
  limits: { cpu: "300m", memory: "256Mi" }
  requests: { cpu: "100m", memory: "128Mi" }